[package]
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
name = "vault_api"
version = "0.1.0"
description = "Interactively visualize your crates.io dependencies."
license = "MIT"
repository = "https://github.com/arpanlaha/vault.git"

[dependencies]
actix-cors = "0.2"
actix-rt = "1.1"
actix-web = { version = "2.0" }
env_logger = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["sync"] }
vault_graph = { path = "../graph" }

[dev-dependencies]
futures = "0.3"
lazy_static = "1.4"
serde_json = "1.0"

[profile.test]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
