[package]
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
name = "vault_api"
version = "0.1.0"
description = "Interactively visualize your crates.io dependencies."
license = "MIT"
repository = "https://github.com/arpanlaha/vault.git"

[dependencies]
env_logger = "0.7"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
vault_graph = { path = "../graph" }
warp = { version = "0.2", features = ["compression"] }

# [dev-dependencies]
# chrono = { version = "0.4" }
# futures = "0.3"
# lazy_static = "1.4"
# serde_json = "1.0"

[profile.test]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
