[package]
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
name    = "vault"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
actix-web      = "2"
arangors       = "0.3"
csv            = "1.1"
dotenv         = "0.15"
futures        = "0.3"
git2           = "0.13"
quote          = "1.0"
r2d2           = "0.8"
r2d2_cypher    = "0.4"
rusted_cypher  = "1.1"
semver-parser  = "0.9"
serde          = "1.0"
serde_json     = "1.0"
syn            = "1.0"
tempfile       = "3.1"
tokio          = { version = "0.2", features = ["macros"] }
tokio-postgres = "0.5"
