[package]
name = "vault"
version = "0.1.0"
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
git2 = "0.13"
tokio-postgres = "0.5"
serde = "1.0"