[package]
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
name = "vault_api"
version = "0.1.0"
description = "Interactively visualize your crates.io dependencies."
license = "MIT"
repository = "https://github.com/arpanlaha/vault.git"

[dependencies]
actix-cors = "0.2"
actix-rt = "1.1"
actix-web = { version = "2.0", features = ["openssl"] }
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1"
env_logger = "0.7"
openssl = { version = "0.10" }
rand = "0.7"
semver-parser = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strsim = "0.10"
tempfile = "3.1"
tokio = { version = "0.2", features = ["macros", "sync"] }

[dev-dependencies]
futures = "0.3"
