name: api

on:
  push:
    paths:
      - api/**
      - .github/workflows/api.yml

defaults:
  run:
    working-directory: api

jobs:
  format:
    runs-on: ubuntu-latest
    name: format
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: nightly-vault-api-format

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-22
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: nightly-vault-api-lint

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-22
          components: clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: nightly-vault-api-test

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-22

      - name: Run tests
        run: cargo test --no-fail-fast --test categories --test compiler --test crates --test keywords --test state -- --test-threads 1 > tests.txt

      - name: Upload tests
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: api/tests.txt
