name: api

on: push

defaults:
  run:
    working-directory: api

jobs:
  bench:
    runs-on: ubuntu-latest
    name: bench
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-nightly

      - name: Install rust toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly

      - name: Run benchmarks
        run: cargo bench --tests

  format:
    runs-on: ubuntu-latest
    name: format
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Run rustfmt
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Run clippy
        run: cargo clippy -- -D warnings
