name: client

on: push

defaults:
  run:
    working-directory: client

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: client-cache

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: client-cache

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: client-cache

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: client-cache

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build
