name: targets

on:
  push:
    paths:
      - targets/**
      - .github/workflows/targets.yml

defaults:
  run:
    working-directory: targets

jobs:
  format:
    runs-on: ubuntu-latest
    name: format
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            targets/target
          key: nightly-vault-targets-format

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-22
          components: rustfmt

      - name: Run rustfmt
        run: cargo +nightly-2020-11-22 fmt -- --check

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            targets/target
          key: nightly-vault-targets-lint

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-11-22
          components: clippy

      - name: Run clippy
        run: cargo +nightly-2020-11-22 clippy -- -D warnings
