name: targets

on: push

defaults:
  run:
    working-directory: targets

jobs:
  format:
    runs-on: ubuntu-latest
    name: format
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            targets/target
          key: nightly-vault-targets-format

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        run: cargo +nightly fmt -- --check

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            targets/target
          key: nightly-vault-targets-lint

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy

      - name: Run clippy
        run: cargo +nightly clippy -- -D warnings
